config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    registrations: "users/registrations"
   }

  resources :stories

  get "@:username/:story_id", to: "pages#show",  as: "story_page"

  get "@:username", to: "pages#user", as: "user_page"
  
  get "/demo", to: "pages#demo"
  root 'pages#index'
end

app/views/shared/frontend/_flash.html.erb
<div class="notification is-primary">
    <%= notice%>
</div>

app/views/shared/frontend/_navbar.html.erb
  <nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
  <%= link_to root_path, class: "navbar-item" do %>
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    <% end %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">

        <% if user_signed_in? %> 
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          <%= avatar(current_user, size: 50) %>
          <%= current_user.email %>
        </a>

        <div class="navbar-dropdown">
        <%= link_to "新規ストーリーを投稿", new_story_path, class: "navbar-item" %>
        <%= link_to "ストーリーズ", stories_path, class: "navbar-item" %>
          <hr class="navbar-divider">
          <%= link_to "プロフィール", edit_user_registration_path, class: "navbar-item" %>
         <%= link_to "ログアウト", destroy_user_session_path, class: "navbar-item", method: "delete", data: {confirm: "ログアウトされますか？"} %>
        </div>
      </div>
        <% else %>
        <%= link_to "新規登録", new_user_registration_path, class: "button is-primary" %>

        <%= link_to "ログイン", new_user_session_path, class: "button is-light" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>