config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    registrations: "users/registrations"
   }

  resources :stories

  get "@:username/:story_id", to: "pages#show",  as: "story_page"

  get "@:username", to: "pages#user", as: "user_page"
  
  get "/demo", to: "pages#demo"
  root 'pages#index'
end

app/views/pages/demo.html.erb
<div data-controller="demo">
  <input type="text" data-target="demo.content">
  <button data-action="demo#pushme">click!</button>
</div>

<div data-controller="demo">
  <input type="text" data-target="demo.content">
  <button data-action="demo#pushit">click!!!!!!</button>
</div>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css" />
  <title>My Medium</title>
</head>
<body>

  <section class="section">
    <div class="container">

      <section class="columns">
        <!-- left -->
        <section class="column">
          <article>
            <figure class="image">
              <img src="https://fakeimg.pl/350x150/f0f0f0" alt="">
            </figure>
            <h2 class="title is-5">Creating a Pipeline to True Workplace Diversity</h2>
            <p class="content">Providing resources, offering acceptance, and involving people of color are keys to making your company more diverse...</p>
            <footer>
              <p>Arielle Wiltz in Modus</p>
              <p>Aug 7</p>
            </footer>
          </article>
        </section>
        <!-- left -->
        <!-- middle -->
        <section class="column">
          <article class="media">
            <figure class="media-left">
              <img src="https://fakeimg.pl/100x100/">
            </figure>
            <div class="media-content">
              <h2 class="title is-5">I Worked for an Amish Reality TV Show</h2>
              <footer>
                <p>Arielle Wiltz in Modus</p>
                <p>Aug 7</p>
              </footer>
            </div>
          </article>
          <article class="media">
            <figure class="media-left">
              <img src="https://fakeimg.pl/100x100/">
            </figure>
            <div class="media-content">
              <h2 class="title is-5">I Worked for an Amish Reality TV Show</h2>
              <footer>
                <p>Arielle Wiltz in Modus</p>
                <p>Aug 7</p>
              </footer>
            </div>
          </article>
          <article class="media">
            <figure class="media-left">
              <img src="https://fakeimg.pl/100x100/">
            </figure>
            <div class="media-content">
              <h2 class="title is-5">I Worked for an Amish Reality TV Show</h2>
              <footer>
                <p>Arielle Wiltz in Modus</p>
                <p>Aug 7</p>
              </footer>
            </div>
          </article>
        </section>
        <!-- middle -->
        <!-- right -->
        <section class="column">
          <article>
            <figure class="image">
              <img src="https://fakeimg.pl/350x200/f0f0f0" alt="">
            </figure>
            <h2 class="title is-5">Creating a Pipeline to True Workplace Diversity</h2>
            <p class="content">Providing resources, offering acceptance, and involving people of color are keys to making your company more diverse...</p>
            <footer>
              <p>Arielle Wiltz in Modus</p>
              <p>Aug 7</p>
            </footer>
          </article>
        </section>
        <!-- right -->
      </section>

      <hr>

      <section class="columns">
        <!-- article list -->
        <section class="column is-two-thirds">

        <% @stories.each do |story| %>
          <article class="media">
            <div class="media-content">
              <h2 class="title is-4"><%= link_to story.title, story_page_path(story.user.username, story), class: "has-text-grey-dark" %></h2>
              <p class="content"><%= story.content %></p>
              <footer>
                <p><%= link_to story.user.username, user_page_path(story.user.username), class: "has-text-grey-dark"%> | 編集記録: <%= time_ago_in_words(story.updated_at) %>
                </p>
              </footer>
            </div>
            <figure class="media-right">
              <img src="https://fakeimg.pl/150x150/">
            </figure>
          </article>

          <% end %>
        </section>
        <!-- article list -->

        <section class="column">
          <h2 class="title is-4">Popular on Medium</h2>
          <hr>

          <article class="media">
            <div class="media-left">01</div>
            <div class="media-content">
              <h3>Difficult Conversation Lessons From a Psychologist Who’s Been Dealing With People</h3>
              <footer>
                <p>Thomas Oppong</p>
              </footer>
            </div>
          </article>
        </section>
      </section>
    </div>
  </section>
</body>
</html>